### ISSUE TITLE
add proper install routine to makefile

### ISSUE THREAD

**Issue by manjaro** [filipe-marques/check-hash#1]
During packaging for Manjaro I noticed we need a proper install routine. As of now we solved it in our [PKGBUILD](https://github.com/manjaro/packages-community/blob/master/checkhash/PKGBUILD). Also you need a proper [desktop file](https://github.com/manjaro/packages-community/blob/master/checkhash/checkhash.desktop).

**Comment by fmf437** [comment]
Thank you for package it !
For fixing it you mean including the two files (PKGBUILD and desktop file) in the check hash project ?
I'm asking this because, never was included a program that I develop in a Linux operating sytem and I never package a program, but I want to learn how to package !

**Comment by fmf437** [comment]
I read the documentation about creating packages and fix the problem and the program has a new organization of folders / files and a new release.
